#Enum integer.

#TurnMotorsOn, = 0
#TurnMotorsOff, = 1
#SetUrgentStopModeEnabled, = 2
#SetUrgentStopModeDisabled, = 3
#SetESCBeepEnabled, = 4
#SetESCBeepDisabled, = 5
#StartTakeoff, = 6
#StartPrecisionTakeoff, = 7
#CancelTakeoff, = 8
#StartLanding, = 9
#CancelLanding, = 10
#ConfirmLanding, = 11
#Reboot, = 12
#StartGoHome, = 13
#CancelGoHome, = 14
#SetHomeLocationUsingCurrentAircraftLocation; = 15

int32 flightActions